# Generated by Django 6.0.6 on 2026-06-08 17:15

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('direccion', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad en libras')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posts.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('verdura', 'Verdura'), ('fruta', 'Fruta'), ('tuberculo', 'Tubérculo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.FloatField(help_text='Cantidad disponible en libras')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('expira_en', models.DateTimeField(default=posts.models.expiracion_default)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('granjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='posts.ItemPedido', to='posts.producto'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.producto'),
        ),
    ]
